### ISSUE TITLE
add flags/configuration to pepr init

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1020]
### Is your feature request related to a problem? Please describe.

If you already know Pepr, going through Pepr init can be burdensome since you already know what you want. Add flags so that scaffolding a new Pepr module can happen quicker. 

### Describe the solution you'd like

- **Given** a Pepr user with knowledge of Pepr wants to scaffold a new module, or maybe even through automation
- **When** they initialize the new module
- **Then** flags or a config file is used to answer the questions in `npx pepr init`

Acceptance Criteria:
- When you issue `npx pepr init` all of the same questions _can_ be overridden if you have flags.
- No change in behavior if flags are not used. 

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by samayer12** [comment]
The current prompt-based input processing happens in `walkthrough.ts`, and called in `src/cli/index.ts`
