### ISSUE TITLE
Ability to rename pepr-*

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1061]
### Is your feature request related to a problem? Please describe.
A recent feedback I got from an open source user testing Pepr was that the company would not go for `pepr-*`, they wanted the ability to rename things more generically. 

### Describe the solution you'd like

- **Given** Someone wants to rename controllers from pepr-* to webapp-*
- **When** they can add configuration
- **Then** the name will reflect the name of their choosing.

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by cmwylie19** [comment]
For now we are going to close this issue. The user that requested this has worked around and found another way

**Comment by thehonker** [comment]
just throwing my $0.02 that this would be a Good Thing that would help drive adoption of this excellent framework
