### ISSUE TITLE
feature flag the sharded queue

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1098]
### Is your feature request related to a problem? Please describe.

The sharded queue will certainly make the reconciliation process go much faster for resources since they do not have to share the same queue. However, downstream users may need time to adjust their modules to accommodate to this enhancement. We need to feature flag this feature so that users can switch when they are ready. In the future we can talk about deprecation and switching to only the sharded queue but we will play it by ear. 

Definition of done:
- [x] docs around the env var
- [x] default to be the standard queue
- [x] an env var to switch to sharded queue

### Describe the solution you'd like

- **Given** the sharded queue comes out for reconcile and module authors are not ready for the change bc it would break their modules
- **When** they update and bring in the newest release
- **Then** they have the ability to turn off the sharded queue should they not be ready for it.

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by btlghrants** [comment]
Working branches:
- pepr  / 1019 (just continuing the partially-complete feature Case started)
    - PR: https://github.com/defenseunicorns/pepr/pull/1025/files
- pexex / 1019 (because identical branch names are easier to correlate across repo)
    - PR: https://github.com/defenseunicorns/pepr-excellent-examples/pull/56/files
