### ISSUE TITLE
esbuild should not package devDependencies in modules

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1103]
### Is your feature request related to a problem? Please describe.
To keep size down, we need to ensure we are not adding dev dependencies to the secret created from the Pepr module.

### Describe the solution you'd like

- **Given** a build occurs
- **When** there are devDependencies, they are excluded
- **Then** the size is smaller since they are not necessary for prod

Links:
- Adding devDeps to externalLibs
- Through env var https://github.com/evanw/esbuild/issues/2377#issuecomment-1179344638 

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by samayer12** [comment]
Note to examine the `src/cli/build.ts` file to see how we're creating secret from the Pepr module.  By examining the output of `npm run build:image`, we can probably see if DevDependencies are making it into the output

**Comment by cmwylie19** [comment]
Good thoughts Sam, although in this case, the image is a separate `esbuild` process entirely. This build pertains to the module author, which exists in `src/cli/build.ts` and is confirmed that `devDependencies` are in fact being included. 

If you make a Pepr module, `npx pepr init`, then add a devDependecy like jest, then examime the output in the  dist folder for the `<module-uuid>.js`, you will be able to reproduce. 

I actually already had this one on my radar and have prior context so I will go ahead and take this one and when we are both back from PTO i will show you how to walk through this in a simple way.

![Image](https://github.com/user-attachments/assets/4ee1087b-9fec-4f39-8925-e1dbf679a96b)

**Comment by cmwylie19** [comment]
Here is the culprit on how this was solved:



![Image](https://github.com/user-attachments/assets/86ae23df-c85c-46b5-87ce-6888de7d2fcc)

Extending this, we are going to keep TS as a devDependencies incidentally introduce a breaking change, all the other devDeps will go

**Comment by btlghrants** [comment]
Just having the devDependencies declared in the deployed package.json doesn't mean that it's contents have been pulled into the module.  Search through the built module code for any of the _content_ of the devDep and you shouldn't see anything out-of-sorts.

Reason being that esbuild isn't including the guts of the devDeps into the built module _unless the module code is calling it_  which... would be an actual problem to be fixed.  As it is now, you've simply got a copy of the package.json that was used to build the module included into the module itself, verbatim.

This isn't something that we actually need to do anything about, IMO.  Are there a few extra characters in the deployed module (i.e. the chars needed to declare the un-included devDeps)?  Yes.  Is it worth writing code to manipulate the built package.json just to remove them?  I'm not so sure (given that this'll be add'l build code that needs to be cared for, etc.).
