### ISSUE TITLE
Duplicated Logic around filterNoMatchReason and shouldSkipRequest, refactor and clean up

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1154]
### Describe what should be investigated or refactored

We should try to align these two function more and ensure they are using the same functions to test

### Links to any relevant code
`src/lib/helpers.ts` && `src/lib/filter.ts`

**Comment by cmwylie19** [comment]
looking into ramda lib

**Comment by btlghrants** [comment]
Yep, going to try to simplify some of that long-form, chained boolean logic by converting various tests into named-for-intention predicate functions -- likely composed via ramda since we're already using it as a utility library in the project (meaning: no new deps!).
