### ISSUE TITLE
Obscure pepr store calls / add a "sensitive" parameter

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/pepr#1173]
### Is your feature request related to a problem? Please describe.

In uds-core we are using the Pepr Store to store Keycloak client registration tokens (sensitive). When we make a call to put the value in the store, the value is logged out if the log level is set to DEBUG or higher.

### Describe the solution you'd like

If a setItem call is made to the store, then Pepr does not log out the value, just the key.

### Describe alternatives you've considered

Alternatively, when the "sensitive" parameter is optionally passed to `setItem`, then the value is obfuscated (i.e. `***`) in logs.

### Additional context

In order to avoid this issue in uds core we reduced the log level of pepr, but in some cases it is nice to increase that log level temporarily for debugging. It would be ideal if that did not expose any sensitive values.

**Comment by cmwylie19** [comment]
After going back and chatting with @mjnagel , he said that an env var that determines globally whether store values are logged in the output would work.
