### ISSUE TITLE
Bring Static Code Analysis Tool into CI

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1198]
### Is your feature request related to a problem? Please describe.

A static code analysis tool could alert us quicker on things that circular dependencies, syntax errors, code quality, and best practices. 

### Describe the solution you'd like

- **Given** a PR is pushed
- **When** CI runs
- **Then** analysis occurs

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by samayer12** [comment]
Internal [blog post](https://defenseunicorns.blogin.co/posts/security-awareness-series-local-sast-scans-vscode-sarif-viewer-and-github-actions-scanning-247869) about running SAST locally. Mention of [CodeQL](https://codeql.github.com/docs/) and [SemGrep](https://semgrep.dev/).

We already use CodeQL, maybe we can revisit the configuration. Grype does vulnerability scanning for us.

**Comment by samayer12** [comment]
This points to a broader organization topic about what tooling belongs across common CI/CD pipelines. Coda page [here](https://coda.io/d/Engineering_dfvozy2Mzwt/Infrastructure-and-Tooling_suxRu6JL#_luCVRTtF) and a slack thread [here](https://defense-unicorns.slack.com/archives/C03QWBD3WUB/p1727975698277609).

I'll opt for some of the low-hanging fruit while we figure out broader policies.

**Comment by samayer12** [comment]
Security scanning:
* [GitHub Security scanning](https://docs.github.com/en/code-security/securing-your-organization/enabling-security-features-in-your-organization/applying-the-github-recommended-security-configuration-in-your-organization) requires action by an org owner.
