### ISSUE TITLE
Update pepr-excellent-examples examples' devDependencies from `pepr init`-ed module

### ISSUE THREAD

**Issue by btlghrants** [defenseunicorns/pepr#1218]
We don't want the excellent example modules to use "the most recent version" of their devDeps, we want them to use "the most recent versions that track what `pepr init` produces" instead.  As a result, we don't want to use dependabot to update the devDep group, we want to write something to do the sync/updates ourselves ( via manual call / CI schedule ).

Follow-on work from https://github.com/defenseunicorns/pepr/issues/1139 .

**Comment by btlghrants** [comment]
Status update:

Dev CLI command added to update specific workspace's devDependencies from local, `pepr init`'d package.json (primary) and/or npmjs.com (secondary).  Command can be invoked like:
```bash
# npm run -w <worksapce> cli -- deps <abs path to init'd mod>/package.json
npm run -w hello-pepr-config cli -- deps $(pwd)/../pepr/pepr-test-module/package.json
```

Can be run against _all_ workspaces in the excellent examples with a command like this:
```
npm run --workspaces cli -- deps $(pwd)/../pepr/pepr-test-module/package.json
```
...but that'll have a return code of 1 (and therefore will fail CI, currently) since not all the examples have a `cli` script in their package.json's (yet).  I'll move to adding that next.

**Comment by btlghrants** [comment]
Examples missing `cli` script in package.json have been updated to include it -- all deps updated (using new cli cmd) & all examples still passing.

**Comment by btlghrants** [comment]
Working on getting the CLI cmd & initial version updates commited to main on [this PR](https://github.com/defenseunicorns/pepr-excellent-examples/pull/152).

Will make a follow-on PR to add an automated workflow to CI.

**Comment by btlghrants** [comment]
Made the follow on [PR](https://github.com/defenseunicorns/pepr-excellent-examples/pull/154), but... forgot that I couldn't actually run it if it's only on a branch.  So I merged it & will be working from `main`-based config file directly.  Ugh.

**Comment by btlghrants** [comment]
Successful update-in-CI run: https://github.com/defenseunicorns/pepr-excellent-examples/actions/runs/11257609683
Successful merge of gen'd PR: https://github.com/defenseunicorns/pepr-excellent-examples/pull/158

So... I think this one's g2g.

**Comment by cmwylie19** [comment]
Reviewed PR and closing this. This is exactly what we were looking for
