### ISSUE TITLE
Document best practices for creating/publishing Pepr modules

### ISSUE THREAD

**Issue by rjferguson21** [defenseunicorns/pepr#123]
As we work through creating/publishing Pepr modules it would be good to have some explanation of the process for packaging a module for use:

Some questions I don't know the answer to:
* Are we expecting modules to be published as Zarf packages, or NPM packages, or both?
* Do we have recommendations around when a Pepr module is deployed to a cluster? I assume it needs to be one of the first things but it would be good to provide example steps for the order of operations that aligns with the intended architecture of Pepr.

Relates to https://github.com/defenseunicorns/pepr-capabilities/issues/28

**Comment by rjferguson21** [comment]
@jeff-mccoy I believe you mentioned something yesterday about a pepr module repo template?  

I think parts of this could be satisfied by capturing the process as part of the template but some of the more ideological questions might still need separate documentation?

**Comment by cmwylie19** [comment]
The current state of the art for publishing your Pepr modules would be through a custom `npm publish` command, the specifics of which (whether you want to use SLS3 or any other provenance) would be up to the module author. 

We are expecting to publish module as standalone repos, nothing stops the module author from publishing to npm but we do not have a unique take.

In terms of the order for an admission controller, currently this is being deployed in UDS as a UDSPackage, which is derived from a ZarfPackage containing the Pepr generated Helm Chart. We have options to Deploy Pepr from a Kube manifest, ZarfPackage or Helm chart but do not have an opinion on which you use. It will be up to your module author to decide based on the deployment environment
