### ISSUE TITLE
Resolve eslint `max-depth` warnings

### ISSUE THREAD

**Issue by samayer12** [defenseunicorns/pepr#1249]
### Describe what should be investigated or refactored

ESlint has several warnings for [max-depth](https://eslint.org/docs/latest/rules/max-depth) violations across the codebase. Resolve these warnings.

### Definition of Done

* There are zero eslint warnings for `max-depth`
* `max-depth` is set to `error` from `warn` in `.eslintrc.json`

### Additional context

Run the linter with `npm format:check`

**Comment by tamirazrab** [comment]
Hi, I'd like to work on this.
