### ISSUE TITLE
Remove deprecated code in `k8s.ts`

### ISSUE THREAD

**Issue by samayer12** [defenseunicorns/pepr#1268]
### Describe what should be investigated or refactored

`k8s.ts` contains several references to types that now live in `types.ts`. We should remove the deprecated code so we do not support unnecessary features.

### Links to any relevant code

* https://github.com/defenseunicorns/pepr/blob/main/src/lib/k8s.ts
* https://github.com/defenseunicorns/pepr/blob/main/src/lib/types.ts

### Additional context
N/A

**Comment by cmwylie19** [comment]
Thanks for opening this back up, when we had a regression in one of the filters we added the deprecated code back. It is on our radars and we are aware. https://github.com/defenseunicorns/pepr/issues/1193

**Comment by cmwylie19** [comment]
more context here https://github.com/defenseunicorns/pepr/pull/1211
