### ISSUE TITLE
create post-admission/mutation builder in the API

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#127]
if you create a kubernetes object in a When() you can't trigger on it in another When consistently since it might not be admitted yet. The idea of flowing between capabilities this way to create objects used further in is one of the biggest 🪄 things pepr should be allowed to do :) 

example:
When(....)
  .Then(async request => {
      // create a new k8s secret with the kubernetes API
});
...
// This When will not find the previously created secret, because it's not persisted until it's fully admitted.
When(...)
  .Then(async request => {
     // read the above secret from the kubernetes API, we're not triggering on the same object from above.
  });

**Comment by jeff-mccoy** [comment]
Can you provide a more concrete example? If you create a K8s resource in one `CapabilityAction`, it will in fact be called by any `CapabilityAction` binding to that create event before it is stored in etcd.

**Comment by bdw617** [comment]
we need this even more. 

with IsCreated()

request.Request.uid is the uid for the admission review, and won't make it into the .metadata.uid of the object. I'm trying to create an ownerReference to automate resource deletion. 

The other option is When(...).IsDeleted() can perform the action of removing the objects I might have created as well. 

which way should we go?

**Comment by bdw617** [comment]
.Validate() and .Mutate() are in. .Watch() is in development.
