### ISSUE TITLE
Investigate flaky `hello-pepr-reconcile-global` test

### ISSUE THREAD

**Issue by samayer12** [defenseunicorns/pepr#1310]
### Environment
Device and OS: CI
App version: `main`
Kubernetes distro being used: `k3d`

### Steps to reproduce
1. Examine failed workflow tests for `hello-pepr-reconcile-global`

### Expected result

Test passes

### Actual Result

Test occasionally fails

### Visual Proof (screenshots, videos, text, etc)

1 hello-pepr-reconcile-global test has failed within the last 200 runs of E2E tests as of 21 Oct 2024.

### Severity/Priority

Low

### Additional Context

Generate a list of recently-failed E2E tests in CI with this command:
`
gh run list --workflow "E2E - Pepr Excellent Examples" --limit 200 --json workflowName,headBranch,conclusion,databaseId --jq '.[] | select(.conclusion == "failure" and .headBranch == "main") | .databaseId' | xargs -I {} gh run view {} --json jobs --jq '.jobs[] | select(.conclusion == "failure") | .name' > ci-failures.log && sort ci-failures.log | uniq -c | sort -r`

**Comment by cmwylie19** [comment]
Closed, fixed in pexex PR
