### ISSUE TITLE
chore: refactor pepr-build-wasm.ts

### ISSUE THREAD

**Issue by schaeferka** [defenseunicorns/pepr#1328]
### Describe what should be investigated or refactored
`pepr-build-wasm.ts` needs to be refactored to remove any unnecessary tests and cleanup any test directories.

### Links to any relevant code
(optional) i.e. - https://github.com/defenseunicorns/pepr/blob/24f1f253b1db4c9d97717c0282b8f39c74d3ace1/README.md?plain=1#L3

### Additional context
Add any other context or screenshots about the technical debt here.

**Comment by cmwylie19** [comment]
covered in #1344
