### ISSUE TITLE
cosign e2e does not work for mac

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1367]
### Describe what should be investigated or refactored

`docker buildx ls` does not exist on a mac, refactor this so it works for mac and linux

### Links to any relevant code
`cosign.e2e.test.ts`

### Additional context
Add any other context or screenshots about the technical debt here.

**Comment by corrosive4354** [comment]
This may be because buildx support is different in some Docker Desktop versions.

In addition, seeing that you use docker to set this up,
I think you can try the [servbay](servbay.com) tool, which is more professional on Mac and supports more than docker.

**Comment by cmwylie19** [comment]
> This may be because buildx support is different in some Docker Desktop versions.
> 
> In addition, seeing that you use docker to set this up, I think you can try the [servbay](servbay.com) tool, which is more professional on Mac and supports more than docker.

Great info! Thanks, we were able to fix it another way. Closing out this issue bc the PR merged yesterday
