### ISSUE TITLE
Refactor `helpers.filterNoMatchReason()` to use FilterChains

### ISSUE THREAD

**Issue by samayer12** [defenseunicorns/pepr#1371]
### Describe what should be investigated or refactored

[helpers.ts](https://github.com/defenseunicorns/pepr/blob/5ba7cc9419953cccc88852c0231a9412abb5b38e/src/lib/helpers.ts#L74)'s `filterNoMatchReason()` uses chained ternary expression to filter data. This is a _very_ similar problem solved with FilterChains in [shouldSkipRequest.ts](https://github.com/defenseunicorns/pepr/blob/5ba7cc9419953cccc88852c0231a9412abb5b38e/src/lib/filter/shouldSkipRequest.ts#L31). We should adopt a similar approach in this file to reduce complexity.

We'll know were done when the `filterNoMatchReason()` function does not flag on any linter warnings and makes a call to `filterChain.execute()` to process data.

### Links to any relevant code

See description.

### Additional context

N/A

**Comment by samayer12** [comment]
Related to #1248

**Comment by btlghrants** [comment]
Note to self: make sure that `src/lib/helpers.ts` complexity warnings go away after this!

**Comment by btlghrants** [comment]
OBE -- the FilterChain pattern impl was rolled back.  Will readdress this refactor in the future, should it become necessary.
