### ISSUE TITLE
Refactor complex implementation in `validate-processor.ts`

### ISSUE THREAD

**Issue by samayer12** [defenseunicorns/pepr#1381]
### Describe what should be investigated or refactored

Resolve the following linter warning:
`  15:8  warning  Async function 'validateProcessor' has a complexity of 13. Maximum allowed is 10  complexity`

### Links to any relevant code

Check out `src/lib/validate-processor.ts`

### Additional context

Related to #1248

**Comment by samayer12** [comment]
`validate-processor.ts` is largely untested on `main`. We'll want to back-fill with some unit tests so that we can confidently refactor. This will provide a faster feedback loop instead of waiting for E2E tests to run.
```
File                  | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
validate-processor.ts |   14.28 |        0 |       0 |   14.28 | 22-85
```

**Comment by samayer12** [comment]
Unstarting this track of work in favor of `v0.40.0` [milestones](https://github.com/defenseunicorns/pepr/milestone/13).

**Comment by btlghrants** [comment]
Pickin' this up!  Today's warnings look like:
```
user@workstation-ubuntu2404:/pepr$ npx eslint src/lib/validate-processor.ts && npx prettier src/lib/validate-processor.ts --check

/pepr/src/lib/validate-processor.ts
  15:8  warning  Async function 'validateProcessor' has a complexity of 13. Maximum allowed is 10  complexity
  62:9  warning  Blocks are nested too deeply (4). Maximum allowed is 3                            max-depth

✖ 2 problems (0 errors, 2 warnings)

Checking formatting...
All matched files use Prettier code style!
```
