### ISSUE TITLE
Add more example capabilities that include the creation of resources

### ISSUE THREAD

**Issue by JaseKoonce** [defenseunicorns/pepr#139]
As a user of this repo I found it difficult to understand how I would implement more complex capabilities like the creation of resources. I believe if there were more examples of capabilities that included a wider scope of options it would be incredibly helpful as I work with Pepr.

**Comment by bdw617** [comment]
in progress!!

**Comment by bdw617** [comment]
@jeff-mccoy is planning an API for this, We have examples for istio, keycloak and authservice. I'm working on an example that properly show how to do tracing, logging, exceptions and metrics.
