### ISSUE TITLE
Type the adjudicators

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#1397]
### Describe what should be investigated or refactored

We need to type the adjudicators to ensure we are asserting on the correct objects

**Comment by cmwylie19** [comment]
There has been substantial work in this issue this sprint, it is an ongoing process. Moving this to the next milestone where work will continue

**Comment by samayer12** [comment]
Task complete. Adjudicators no longer flag when running `npm run format:check` with the config provided by #1364
