### ISSUE TITLE
Re-impliment `pepr test` with new workflow

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/pepr#14]
Now that the SDK is embedded/loaded by a Pepr Module (vs the other way around), we need to update the test flow to handle this--or possibly even removing it since `pepr dev` does a lot of this for you.

**Comment by cmwylie19** [comment]
This is the Kubernetes SDK, since this has been closed, right @jeff-mccoy ?

**Comment by cmwylie19** [comment]
Closing in favor of tracking in #301 thanks!
