### ISSUE TITLE
QOL changes

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#143]
1. pepr cli with any noun verb it doesn't know should display help. IE: `pepr help` 
2. `pepr dev` should validate the version in the package.json is compatible. IE: an old version of the pepr cli should error if the package.json has a newer version
3. `pepr` should be able to import a CRD as a Kind. Best examples are the networking.istio.io objects, This should be part of the build/dev process. like `pepr import crd virtualservices.networking.istio.io`
4. `pepr dev` should make sure there aren't multiple mutatingwebhooks with the same endpoint name

**Comment by jeff-mccoy** [comment]
going to move these 2 to their own issues since they are fairly unrelated. Can you clarify #4? Not sure I understand what is being asked for.

**Comment by jeff-mccoy** [comment]
https://github.com/defenseunicorns/pepr/issues/146
https://github.com/defenseunicorns/pepr/issues/147
https://github.com/defenseunicorns/pepr/issues/148
https://github.com/defenseunicorns/pepr/issues/149
