### ISSUE TITLE
Pepr Load Test ( Reconcile()-based ) Nightly CI

### ISSUE THREAD

**Issue by btlghrants** [defenseunicorns/pepr#1431]
### Request ###

Add a nightly CI job to test Pepr controller's resource usage under moderate load.

### Background ###

Relates #1350 

Follow on work to run the new load test scripts in CI, nightly.

### Definition of done ###

- [x] A nightly CI workflow
- [x] Workflow result includes artifacts containing load test data files & generated graphs
- [ ] ( nope --> ) test graph displayed as part of  [$GITHUB_STEP_SUMMARY](https://github.com/orgs/community/discussions/101814) (if possible).

**Comment by btlghrants** [comment]
test

**Comment by btlghrants** [comment]
Load test ran overnight and has generated an appropriate dataset + graph: https://github.com/defenseunicorns/pepr/actions/runs/11906627631

Have a snag on trying to get the graph png to render in GH UI via the `$GITHUB_STEPS_SUMMARY` facility though:  because the only persistent place the png lives is as a workflow artifact, and GH only exposes artifacts as .zips, I can't link to it as an image directly (i.e. '[]()', or '<img src=''" />'). 

Also, looks like GH won't honor data URIs so I can't seem to find a way to sneak the picture into the output markdown, so... going to call this one as done as it can be.  Going to have to chat other ideas about for easily-accessible graphs through with the team.

**Comment by cmwylie19** [comment]
done in #1445
