### ISSUE TITLE
pepr should be able to import a CRD as a GroupVersionKind.

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/pepr#148]
Best examples are the networking.istio.io objects, This should be part of the build/dev process. like pepr import crd virtualservices.networking.istio.io

**Comment by bdw617** [comment]
https://github.com/tommy351/kubernetes-models-ts

This project does a decent job at it. It might be better to start with the raw CRD file. This way you don't need a cluster with the CRDs installed to perform this action.

**Comment by cmwylie19** [comment]
Does Generic Kind satisfy this or is the ask something different? @jeff-mccoy

**Comment by jeff-mccoy** [comment]
Ideally you would use the unicorn kind pattern in hellopepr to register the new resource type

**Comment by cmwylie19** [comment]
Do you see this as being enough when the user creates the class extending `GenericKind` and registering that kind? 

Or you see a world where this logic is abstracted away and the user writes in the `package.json` that they would like to register and operate on a specific kind?

**Comment by cmwylie19** [comment]
This will be fixed by https://github.com/defenseunicorns/kubernetes-fluent-client/pull/24.

We will still need to document how to do this in Pepr
