### ISSUE TITLE
Recommendations from Pepr Usability Testing

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/pepr#151]
## Recommendations

- [x] Add Pre-requisites to [Read.me](http://read.me/)
- [x] Add ```$ npm i -g pepr``` to [Modules page](https://github.com/defenseunicorns/pepr/blob/main/docs/module.md#module-development-lifecycle)
- [x] Add information about validating webhooks - difference between mutating vs validating webhooks
- [x] Add Troubleshooting section
    - [ ] Note the npm-ism (with versions) Add that npx can be used to easily keep npm installed link to external docs)
- [ ] Tutorial of how to use chatGPT to help you use paper (Internal blogin)
- [x] Rename links from “Here” to a name describing the link to increase accessibility.
- [x] Request for a common set of core Pepr modules, Delivery can consume common modules and modify not start from scratch
    - [ ] Survey top 5 common things that are complicated in delivery

**Comment by cmwylie19** [comment]
Closing this as these tasks are now complete
