### ISSUE TITLE
Raw does does exist for IsDeleted()

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#155]
assume it's due to the format of the admissionreview. A workaround would be to get the object directly, not hard, but a bit inconsistent. Maybe there needs to be a PeprDeleteRequest<> that just doesn't have Raw?

**Comment by bdw617** [comment]
documentation issue, the old object is available in .OldResource, not very intuitive. versus .Raw for ones you can change

**Comment by jeff-mccoy** [comment]
fixed in #167
