### ISSUE TITLE
Init Capability for Pepr (like a [safer] IIFE or init() in Go)

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#157]
An async self instantiating init capability in Pepr. (Similar to async IIFE without side effects)

_Reasoning_
**Given** you are using Pepr to create a module to replace the Zarf Agent, and a pertinent secret is attached to the pod as volume that must be read before anything else can happen,
**When** the webhook spins up,
**Then** it should have an init capability to read the secret contents and block any further processing until init capability finishes.

**Comment by cmwylie19** [comment]
This is a nice to have but I am working around this using a helper function.

**Comment by bdw617** [comment]
it does need some kind of init! I'm going to +1 this. @jeff-mccoy and I were talking about this earlier. Specifically I want to maybe do some auto-detect for open telemetry endpoint and for setting up metrics. The question is do you want some of this in the core or the capabilities? I think the answer is core, but the capabilities should have a config init as well.

**Comment by bdw617** [comment]
a scenario that is valid is that pepr wants to write tracing out to a service that may or may not be in cluster, and may or may not be deployed at the time of the pepr module. Not only we need an init, but we need it to be tried over and over again until it works to fit in well with Kubernetes consistency patterns.
