### ISSUE TITLE
Support for base64 encoding/decoding non-ASCII characters in Secret data

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns/pepr#219]
**Given** I need to read/write data that contains non-ASCII characters from/to a Kubernetes secret
**When** I use Pepr to read/write the data
**Then** Pepr encodes and decodes the data for me

Context:

The current behavior of Pepr not encoding/decoding non-ASCII characters is intentional, see https://github.com/defenseunicorns/pepr/pull/131. That PR relates to issue https://github.com/defenseunicorns/pepr/issues/129, which may be related to https://github.com/rancher/rancher/issues/27439.

**Comment by lucasrod16** [comment]
Relevant code: https://github.com/defenseunicorns/pepr/blob/main/src/lib/utils.ts

**Comment by lucasrod16** [comment]
The root cause of https://github.com/rancher/rancher/issues/27439 was that the Rancher UI was attempting to display binary data as text data, resulting in data corruption when users would use the UI to update their secrets that contained binary data.

See https://github.com/rancher/rancher/issues/27439#issuecomment-641624517

The fix for this was to only render/display ASCII-like values in the UI, and to prevent editing non-ASCII-like secret data via the UI

See https://github.com/rancher/dashboard/pull/5791

Because that issue is related to how the Rancher UI displays binary data (and not related to properly base64 encoding/decoding binary data), Pepr should be able to safely base64 decode/encode binary data.

**Comment by bdw617** [comment]
PR is merged

**Comment by lucasrod16** [comment]
> PR is merged

The PR has not been merged yet: https://github.com/defenseunicorns/pepr/pull/228

**Comment by cmwylie19** [comment]
Hey, i am going to close this but happy to open it back up if we need to. Thanks!
