### ISSUE TITLE
Deployment improvements.

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#280]
### limited deployment options
currently `npx pepr build` will create a raw manifest and a zarf package. This is a great option but we need more:

### ideas:
1. I think it should generate a helm chart, this will make it easier for people to integrate pepr into autoscaling, proper naming, using a different namespace (if needed), locking down the cluster role bindings. Also including easy environment variables we can pass in via the values file.
2. we should consider a deployment that splits cluster role bindings, CRD, needed, in the event we work with openshift. 
3. we also will need a way for people to deploy larger capabilities that might contain additional JS modules that don't fit into a Kubernetes secret. 
4. naming the objects with a UUID isn't awesome, those should be defined in the module spec, we can check to make sure it doesn't violate naming in Kubernetes.

**Comment by jeff-mccoy** [comment]
I'd rather move things away from (rather than towards) Helm in general. SSA gives us a lot of power and I think is the great future for us. That would also allow to make the whole deployment process far more flexible without additional complexity. See the [Kubernetes Fluent Client](https://github.com/defenseunicorns/kubernetes-fluent-client) README for examples:

```typescript
import { K8s, kind } from "kubernetes-fluent-client";

// Let's create a random namespace to work in
const namespace = "my-namespace" + Math.floor(Math.random() * 1000);

// Create a few resources to work with: Namespace, ConfigMap, and Pod
Promise.all([
  // Create the namespace
  K8s(kind.Namespace).Apply({
    metadata: {
      name: namespace,
    },
  }),

  // Create the ConfigMap in the namespace
  K8s(kind.ConfigMap).Apply({
    metadata: {
      name: "my-configmap",
      namespace,
    },
    data: {
      "my-key": "my-value",
    },
  }),

  // Create the Pod in the namespace
  K8s(kind.Pod).Apply({
    metadata: {
      name: "my-pod",
      namespace,
    },
    spec: {
      containers: [
        {
          name: "my-container",
          image: "nginx",
        },
      ],
    },
  }),
])
  .then(() => console.log("done!"))
  .catch(err => {
    console.error(err);
  });
```

Someone would have to import an absolutely massive JS library to trigger that, perhaps for those libraries (think the ridiculous beast that AWS) we look at how those are imported first, e.g. using default import vs named import.

**Comment by jeff-mccoy** [comment]
Since we already have `npx pepr deploy` it might be interesting to make that extensible using the Fluent Client if teams want more power.

**Comment by cmwylie19** [comment]
Given what has been said in the above convo, we can look into number number 2 for OpenShift, which would be along the lines of creating the correct `securityContexts` in order for it to pass through the OpenShift's ValidatingAdmissionWebhooks. Link to relevant [docs](https://docs.openshift.com/container-platform/4.13/authentication/managing-security-context-constraints.html).

**Comment by cmwylie19** [comment]
Number 4 sees like it is tracked [here](https://github.com/defenseunicorns/pepr/issues/281)

**Comment by cmwylie19** [comment]
All of this is now accounted for in:
- (1) We have not had any user ask for this but if they do they can `npx pepr build` and put the manifests into the templates directory.
- (2) Pepr's Deployments use securityContext on [pods](https://github.com/defenseunicorns/pepr/blob/e7ba00436d0a8a2e68eb7c6b614e373e88243248/src/lib/assets/pods.ts#L76) and [containers](https://github.com/defenseunicorns/pepr/blob/e7ba00436d0a8a2e68eb7c6b614e373e88243248/src/lib/assets/pods.ts#L117)
- (3) [Mount multiple secrets as a way to increase module size ](https://github.com/defenseunicorns/pepr/issues/494)
- (4) https://github.com/defenseunicorns/pepr/issues/281 optional unique name
