### ISSUE TITLE
allow an optional unique_name instead of a uuid for the module name

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#281]
### Is your feature request related to a problem? Please describe.
the uuid is great for being unique, but for the platform engineer, having objects named `pepr-<uuid>-<stuff>` is great for knowing what it is, it's especially worst if there are multiple modules deployed.

### Describe the solution you'd like

Leave the UUID in as is, allow for another optional parameter called UNIQUE-NAME, that will be used instead of the UUID if it's populated.

**Comment by jeff-mccoy** [comment]
I think maybe it would be cleaner to rename the config entry and document better. Right now you can change the value of `pepr: uuid` in the `package.json` (a UUID is not actually required). But maybe we change it from `uuid` -> `uniqueID` or similar?

**Comment by cmwylie19** [comment]
You can supply anything in the UUID field in the package.json, this is already a possibility and it is use at your own risk.
