### ISSUE TITLE
Revise npx pepr update workflow

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#287]
### Is your feature request related to a problem? Please describe.
Revise pepr update workflow so it won't clobber changes the user may have made to hello-pepr.ts or re-create it automatically if the user has already moved on from it. I'm labeling this a bug since it can clobber work the user has done.

### Describe the solution you'd like

The workflow for update needs to be revised, it's fragile if they've pulled in other libraries, and some version to version upgrades will have version incompatibilities in the package.json file

We need to make this easier for the end user to interactively know what changes will be made before they are made and give them the option to apply them. 

 Also verify the pepr.onError action to make sure it's valid, if not, prompt the user for the change.

**Comment by cmwylie19** [comment]
Given that we are moving hello-pepr out of core, we are going to close this.
