### ISSUE TITLE
find scaling limitations of pepr

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#289]
### Is your feature request related to a problem? Please describe.

Pepr has been mostly tested in smaller Kubernetes environments. We do some amazing integration work with k3d running on our laptops, but we really should perform some testing on larger clusters, larger number of events, and publish the metrics to help people decide if this is for them.

**Comment by cmwylie19** [comment]
On hold as we changed the watch and this will affect scaling

**Comment by cmwylie19** [comment]
This is being done using load testing, soak testing nightly. For now, we are going to close this, should we have a more specific ask we will create a new, well-defined issue.
