### ISSUE TITLE
metrics and traces

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#290]
### feature request

update the metrics exporting from pepr to include more relevant information, also make pepr emit open telemetry traces. also allow capabilities to extend both of these for capability specific information.

**Comment by cmwylie19** [comment]
We have added [KFC Informer metrics](https://github.com/defenseunicorns/pepr/pull/983) and we are not considering OTEL traces at this point until some of our downstream users ask. As far as we know these metrics provide a comprehensive overview of how Pepr is operating in the cluster. If you need specific metrics feel free to open a new issue. Currently we do not have any downstream users using traces but it is something we would consider should the need arise.

**Comment by cmwylie19** [comment]
closed in. #983
