### ISSUE TITLE
We should get a docs site up... even if it's simple.

### ISSUE THREAD

**Issue by btlghrants** [defenseunicorns/pepr#292]
### Describe what should be investigated or refactored
I'd love to see an automation-fed, user-facing documentation / training site.

### Links to any relevant code
Similar site f/ Zarf: https://docs.zarf.dev/docs/zarf-overview

### Additional context
Seems pretty important for impression management / being taken seriously by consumers.

**Comment by cmwylie19** [comment]
Related link for Hugo site: https://github.com/defenseunicorns/doc-site-template

**Comment by btlghrants** [comment]
Bryan put a PR in to kick this off: https://github.com/defenseunicorns/pepr/pull/328/files

**Comment by cmwylie19** [comment]
check! https://pepr-docs.netlify.app/docs/
