### ISSUE TITLE
Watch() will get replayed events if kubernetes closes the connection to the underlying REST API call

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#295]
### Steps to reproduce
1. start k3d
2. start pepr in dev
3. see the store get initialized.
4. wait 10 minutes
5. the same event happens again

### to fix this
the easiest possible solution is to keep track of the last event you got from the server, let them persist through the network close, and not call the user callback if you get it again.

other solutions would be to implement this in the kubernetes-fluent-client as well, basically the same thing. 

### not resilient to:
pepr controller pod restarting, there's no persistence here.

**Comment by cmwylie19** [comment]
This is what `bookmarks` do in the Kubernetes API Server https://kubernetes.io/docs/reference/using-api/api-concepts/#watch-bookmarks
