### ISSUE TITLE
make pepr controller (Watch()) scalable and fault tolerant

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#296]
###problem

Right now, the pepr controller handles all the Watch() actions, which is a single pod, so depending on the user's implementation of their callbacks could cause a slow down and unbalanced pod resource usage.

### Describe alternatives you've considered
1. have the controller not actually execute the callbacks but call the pepr callback in the deployment (advantage: better distribution of load, disadvantage: an extra network hop). Keep the controller in typescript or rewrite the controller in golang (doesn't actually solve a problem unless there are scaling issues with the IO in typescript monitoring kubernetes object modifications)
2. build a fault tolerant model for the controller which would require some sort of leader election (this is heavy weight, and not necessarily helpful since kubernetes will always send the current state of the object as the first message of a watch).
3. read from the audit log, which shouldn't lose any intermediate events persisted to etcd. (this is cumbersome, but keep the idea alive in case we need it for potential customers)

**Comment by cmwylie19** [comment]
Completed in https://github.com/defenseunicorns/pepr/pull/453
