### ISSUE TITLE
Create a library of helper functions that make working with Pepr easier.

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#299]
### Is your feature request related to a problem? Please describe.
 
Could be worth adding it to the `PeprValidateRequest` class as something like `request.getContainers()` or at least as a helper function you can import. 

### Describe the solution you'd like

- **Given** you are in a validate block 
- **When** parameter name is passed into the callback
- **Then** the parameter has a helper function `.getContainers()`

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

### Additional context

```typescript
// Returns all containers in the pod
export function containers(request: PeprValidateRequest<a.Pod>) {
  return [
    ...(request.Raw.spec?.containers || []),
    ...(request.Raw.spec?.initContainers || []),
    ...(request.Raw.spec?.ephemeralContainers || []),
  ];
}
```

**Comment by cmwylie19** [comment]
Relates to: #245 #279

**Comment by cmwylie19** [comment]
Could be worth adding it to the PeprValidateRequest class as something like request.getContainers() or at least as a helper function you can import. Thoughts?

```typescript
// Returns all containers in the pod
export function containers(request: PeprValidateRequest<a.Pod>) {
  return [
    ...(request.Raw.spec?.containers || []),
    ...(request.Raw.spec?.initContainers || []),
    ...(request.Raw.spec?.ephemeralContainers || []),
  ];
}
```
