### ISSUE TITLE
Add flags to `pepr init` to allow creation of `--deployment` / `--library` modules.

### ISSUE THREAD

**Issue by btlghrants** [defenseunicorns/pepr#307]
### Is your feature request related to a problem? Please describe.

`pepr init` currently creates what I'm thinking of as a "deployment" module (i.e. a Pepr module intended for direct deployment to a cluster) -- it uses a pepr.ts to build & does not override npm package entrypoint within the package.json dev:build script.

In contrast to that, the [pepr-keycloak-authsvc](https://github.com/defenseunicorns/pepr-keycloak-authsvc) project uses a slightly modified layout that is both:
1) hand-rolled, and
2) a modification of the standard `pepr build` process to produce a Pepr module that is intended _not_ for direct deployment but instead for reuse via NPM import  (a.k.a. what I'm thinking of as a "library" module) -- it uses an index.ts to build & overrides npm package entrypoint within the package.json dev:build script.

This second pattern is useful and I'd like to see it formalized.

### Describe the solution you'd like

- **Given** an updated `pepr` command
- **When**  I run `pepr init` or `pepr init --deployment`
- **Then** I should see the "deployment" pattern in use (i.e. just the same as running a naked `pepr init` does now)
&nbsp;
- **But When**  I run `pepr init --library`
- **Then** I should see the "library" pattern in use (i.e. similar to the way the [pepr-keycloak-authsvc](https://github.com/defenseunicorns/pepr-keycloak-authsvc) project does now)
&nbsp;
- **And** I should be able to navigate to some docs page that describes module type differences / usage.

### Describe alternatives you've considered
Haven't really -- just trying to formalize the pattern we're already using / make it easier / nicer to use the "--library" module pattern.

### Additional context
- [pepr-keycloak-authsvc](https://github.com/defenseunicorns/pepr-keycloak-authsvc) pepr.ts vs index.ts / package.json dev:build script.

**Comment by schaeferka** [comment]
No longer needed after discussion with team.
