### ISSUE TITLE
fix: PeprStore not deployed when using OnSchedule with multi-capability module

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns/pepr#421]
### Environment
Device and OS: M1 Mac
App version: v0.18.1
Kubernetes distro being used: K3d and EKS

### Steps to reproduce
1. `k3d cluster create`
2. `git clone --branch OnSchedule-refactor https://github.com/defenseunicorns/zarf-init-aws.git && cd zarf-init-aws`
3. `npx pepr deploy --confirm`

Note that the `Watch()` controller gets deployed as observed by the `-watcher` suffixed Deployment in the `pepr-system` namespace, but there is only one PeprStore. If you modify `pepr.ts` to only register/deploy the `OnSchedule` capability (`ECRCredentialHelper` in this example), both the `Watch()` controller and the second PeprStore get deployed and functions as expected.

### Expected result
Pepr deploys a dedicated PeprStore resource for the `OnSchedule` capability and successfully runs/executes the schedule code when used in a module with other capabilities.

### Actual Result
Pepr does not deploy a dedicated PeprStore resource for the `OnSchedule` capability when used in a module with other capabilities, resulting in the `OnSchedule` code not running/executing.

### Visual Proof (screenshots, videos, text, etc)

1. Pepr hangs on `Registering schedule store for ecr-credential-helper` when the `OnSchedule` capability is listed first with another capability and does not create a PeprStore resource for the schedule:

<img width="1672" alt="Screenshot 2023-12-05 at 9 57 08 PM" src="https://github.com/defenseunicorns/pepr/assets/87675701/528b4854-aee2-48bb-bb50-a244a0a2b073">

2. Pepr shows no output related to successfully setting up the `OnSchedule` capability when listed after another capability and does not create a PeprStore resource for the schedule:

<img width="1672" alt="Screenshot 2023-12-05 at 9 58 12 PM" src="https://github.com/defenseunicorns/pepr/assets/87675701/7fca4522-89bf-4d30-b6a3-0ecdb384f3e5">

3. Pepr creates a second PeprStore resource and successfully runs/executes the `OnSchedule` capability when it is the only capability in the module:

<img width="1672" alt="Screenshot 2023-12-05 at 9 59 14 PM" src="https://github.com/defenseunicorns/pepr/assets/87675701/ef43962f-38ec-45a8-9366-9dabcac87b12">

**Comment by cmwylie19** [comment]
Thanks for reporting this!
