### ISSUE TITLE
Exemptions/Exceptions in Pepr Core

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#430]
### Is your feature request related to a problem? Please describe.

Have an exemption clause where specific failing objects are allowed to pass through admission. This can already be done in Pepr Core today through filters. This issue is here for tracking purposes.

### Describe the solution you'd like

- **Given** an exemption is created
- **When** a failing object that is on the exemption list hits Admission
- **Then** it is approved and goes into the cluster

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by Racer159** [comment]
@cmwylie19 should this issue be closed?

**Comment by cmwylie19** [comment]
> @cmwylie19 should this issue be closed?

oh yes, thought automation was supposed to do it for us so need to update that!

**Comment by cmwylie19** [comment]
We closed this issue because having some kind of backdoor could jeopardize the module that was written with Pepr. We shifted this responsibility to the Module author.
