### ISSUE TITLE
spike: npx pepr -- how do we update the version?

### ISSUE THREAD

**Issue by btlghrants** [defenseunicorns/pepr#546]
Personal experience -- and Issues like [#530](https://github.com/defenseunicorns/pepr/issues/530) -- have shown that the way NPX deals with versions of installed binaries tends to surprise people:

- `npx pepr` installs the most recent version available
- `npx pepr@version` will install the requested (potentially newer) version
- `npx pepr --version` (i.e no version tag) will show that npx still uses the _older, origninally installed version._

Our answer (i.e. #530) is to instruct people to clear their machine's .npm cache (i.e. where npx installs things), but... maybe there's a better way?

It would be nice if there was a command that users could run (sort of like `npx pepr update`) that would install & relink a newer `npx pepr`-able version.

**Comment by cmwylie19** [comment]
closing this, we can update this if we need in the future but it seems like people are updating with dependabot and `npx pepr update`
