### ISSUE TITLE
Ability to choose image during build/deploy

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#565]
### Is your feature request related to a problem? Please describe.
Now that Pepr's controller is in Iron Bank, we need the ability to choose images at build/deploy time in the cli 

### Describe the solution you'd like

- **Given** you are building or deploying using `npx pepr` and you want to use the IB image
- **When** you issue the command, there is a subcommand to decide which image to use
- **Then** the manifests contain the chosen image.

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by zachariahmiller** [comment]
As an example for reference, we use zarf flavors to drive which sets of images get built into a given uds-core ref https://github.com/defenseunicorns/uds-core/blob/main/tasks/create.yaml a similar pattern is used in the other uds packages

The generated pepr zarf package from `npx pepr build` could either implement flavors similar to what we do in the uds-core packages, or just support a flag. The latter is probably more intuitive. If that is the case though, irrespective of the name of the flag it would be nice if we could pass it the same way. Like:

`npx pepr build --image $FLAVOR`

where flavor would be "upstream" or "registry1" if the flag is passed. Then the build can retain the existing behavior of `npx pepr build` today that defaults to the ghcr image
