### ISSUE TITLE
TODO: add example kubectl commands to the pepr hello world capability demo.

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#67]
IE: 

kubectl create ns pepr-demo
kubectl create configmap  example-1 -n pepr-demo

**Comment by jeff-mccoy** [comment]
you wouldnt create those, you'd `kubectl apply -f`. We currently have this info in 3 places:

1. The [main readme](https://github.com/defenseunicorns/pepr#wow-too-many-words-tldr)
2. The [Module Docs](https://github.com/defenseunicorns/pepr/blob/main/docs/module.md#module-development-lifecycle)
3. The `HelloPepr` generated capability in every module.

Should there be something else, I think these 3 places might be sufficient?

![Screenshot 2023-04-27 at 1 23 26 PM](https://user-images.githubusercontent.com/882485/234957671-c0e526fa-6f41-4ae1-92cd-315692fa5085.png)

![Screenshot 2023-04-27 at 1 24 05 PM](https://user-images.githubusercontent.com/882485/234957684-278d591a-606f-4ced-9272-521ef8ad62b4.png)

![Screenshot 2023-04-27 at 1 22 54 PM](https://user-images.githubusercontent.com/882485/234957706-c9d8516a-dc19-4eb7-a6c7-bf087ebca20a.png)
