### ISSUE TITLE
Make waitForConfigMap Wait Longer Each Time It Tries Again- Exponential backoff

### ISSUE THREAD

**Issue by naveensrinivasan** [defenseunicorns/pepr#684]
#### Problem:
Right now, in our code, when we try to get a ConfigMap https://github.com/defenseunicorns/pepr/blob/db0d8ae661a75ae2a19b2e9f38dfb0b01b56be1a/journey/k8s.ts#L54-L61 we wait 2 seconds and try again. We keep doing this the same way, no matter how many times we have to try.

#### Why Change?
Reduces trashing.

#### How to Change:
Exponential backoff

#### Example:
Here's a simple way to change it:

```typescript:journey/k8s.ts
export async function waitForConfigMap(namespace: string, name: string, tryCount = 0) {
  try {
    return await K8s(kind.ConfigMap).InNamespace(namespace).Get(name);
  } catch (error) {
    const waitTime = Math.min(2 ** tryCount, SOME_MAX_TIME);
    await sleep(waitTime);
    return waitForConfigMap(namespace, name, tryCount + 1);
  }
}
```

**Comment by cmwylie19** [comment]
Hi @naveensrinivasan , exponentialBackup is indeed a great feature to reduce thrashing and network utilization but this is in our journey tests, like similar to e2e tests. This would exponentially increase the time it takes to run them. Currently there is not any problem with our e2e tests in terms of network pressure.

**Comment by naveensrinivasan** [comment]
> Hi @naveensrinivasan , exponentialBackup is indeed a great feature to reduce thrashing and network utilization but this is in our journey tests, like similar to e2e tests. This would exponentially increase the time it takes to run them. Currently there is not any problem with our e2e tests in terms of network pressure.

I was ignorant 😄 . I thought this was the API.

 So, is this being used only for tests?

**Comment by cmwylie19** [comment]
> > Hi @naveensrinivasan , exponentialBackup is indeed a great feature to reduce thrashing and network utilization but this is in our journey tests, like similar to e2e tests. This would exponentially increase the time it takes to run them. Currently there is not any problem with our e2e tests in terms of network pressure.
> 
> I was ignorant 😄 . I thought this was the API.
> 
> So, is this being used only for tests?

It is only being used for tests but that was a _great idea_ that we really appreciated. Thanks for keeping us under your watchful eyes. Welcome to any and all suggestions.
