### ISSUE TITLE
TODO: DEMO create a self-signed cert within the cluster

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/pepr#69]
https://github.com/istio-ecosystem/authservice/blob/master/bookinfo-example/scripts/generate-self-signed-certs-for-ingress-gateway.sh

maybe not, look at cert-manager too?

**Comment by jeff-mccoy** [comment]
We could include [node-forge](https://www.npmjs.com/package/node-forge) in the controller? It's already included in the CLI, but not included in the final controller for use by other Pepr Modules.

**Comment by bdw617** [comment]
I'm feeling less like we need this, going to close it for now
