### ISSUE TITLE
document mutate helpers 

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#752]
### Describe what should be investigated or refactored

1. Break out User Guide -> Actions ->  into new lower levels for (mutate, validate, reconcile, watch)
2. Document mutate helpers like SetLabel, SetAnnotation, RemoveAnnotation, RemoveLabel and they should be in User guide -> Actions -> Mutate
3. Reference the SDK Helpers link

### Additional context
Add any other context or screenshots about the technical debt here.

**Comment by schaeferka** [comment]
Closed by #774
