### ISSUE TITLE
flag to configure time stamps in Pepr 

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#795]
### Is your feature request related to a problem? Please describe.

When debugging across kube-apiserver logs, cluster audit logs, and Pepr logs the Pepr logs use a timestamp and we have to convert them to UTC. We want this to be configurable. 

### Describe the solution you'd like

- **Given** I want the Pepr logs to be in UTC format
- **When** I configure the controller
- **Then** the logs are printed in the UTC format 

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

**Comment by btlghrants** [comment]
It looks like this _should_ just involve adding a bit of config to Pino -- and, of course, then figuring out which test break:

Config docs:
- https://getpino.io/#/docs/api?id=pinooptions-destination-gt-logger

Config option "timestamp" can take a function arg:
- https://getpino.io/#/docs/api?id=timestamp-boolean-function

Which looks like it can take a "pino.stdTimeFunctions.isoTime" arg that'll do what we want..?
- https://getpino.io/#/docs/api?id=pino-stdtimefunctions
