### ISSUE TITLE
Calling Store.clear() (sometimes) corrupts the Pepr Store

### ISSUE THREAD

**Issue by btlghrants** [defenseunicorns/pepr#796]
Running all e2e tests for the `hello-pepr-store` excellent example will fail intermittently _IF_ the commented out scenarios in 
[store.e2e.test.ts](https://github.com/defenseunicorns/pepr-excellent-examples/blob/main/hello-pepr-store/capabilities/store.e2e.test.ts) and [store.ts](https://github.com/defenseunicorns/pepr-excellent-examples/blob/main/hello-pepr-store/capabilities/store.ts) are uncommented.

It appears that the call to `Store.clear()` is somehow "corrupting" the store itself --  often, after calling that method, the Pepr logs will just begin listing repeated 422 (Unprocessable Entity) when trying to update the store... and it never self-corrects.

What's going on with Store.clear()?

**Comment by cmwylie19** [comment]
this is now a non-issue. Tested and CI is passing
