### ISSUE TITLE
Pepr Store Keys Need Sanitization

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#915]
### Describe what should be investigated or refactored
Certain keys are not making it into the store, the patch operation is returning `422`.

![image](https://github.com/defenseunicorns/pepr/assets/1096507/70abccb2-d72b-4a03-a115-e2fba5cbfa5a)

We need a way to sanitize the key so that the patch operation succeeds and users of the store can get their data in a consistent manner.

```plaintext
We ran into an issue in a few spots where we accept arbitrary keycloak client ids in our Package CR and then use those in other resources without "sanitizing" them. One of those places was the pepr store - we were setting weird client IDs like https://google.com/ for testing and then our pepr store key had that in it and failed during set. Just want to make sure we know what is allowed for those key names.
```

Reproduce:

```ts
When(a.Pod)
  .IsCreatedOrUpdated()
  .Mutate(po => {
    Log.info("Pod created or updated", po);
    //Store.setItem(`${po.Raw.metadata!.name}`, "a");
    Store.setItem(`https://google.com-${po.Raw.metadata!.name}`, "bcd");
  });
```

Definition of done:
- Folks can put in keys to the store like `https://google.com-${po.Raw.metadata!.name}`, the store sanitizes them before the pack, and they can get them back out by the same key (the store sanitizes the Store.getItem). 

### Links to any relevant code
`/src/lib/controller/store.ts`

### Additional context
Add any other context or screenshots about the technical debt here.

**Comment by mjnagel** [comment]
This would be a pretty big value add for uds-core. We started to go down the route of figuring out our own sanitization but were struggling with:
- What names are valid for the store
- How should we handle sanitization in such a way that keys maintain uniqueness (i.e. if there is a length limit and you just trim to 4 characters how do you ensure that `foobar` ends up different from `foobaz`

If pepr handled this in a way that we could just set and keys and be guaranteed that set/get calls would succeed and not retrieve the wrong value that would be great for our use case.

**Comment by cmwylie19** [comment]
In researching other edge-cases, size does not seem to be a limitation.

```ts
    let longString = 'a'.repeat(253);
    const longerString = longString.repeat(1000);
    Store.setItem(longerString, longString);
```

**Comment by cmwylie19** [comment]
Moving to the next milestone since we need to plan with UDS Core how to roll this out to prod users
