### ISSUE TITLE
refactor the store to share code

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/pepr#959]
### Describe what should be investigated or refactored

The controller Store has several nested function that are extremely similar, I think we can refactor the store code and reduce a lot of duplicated code. 

### Links to any relevant code
https://github.com/defenseunicorns/pepr/blob/main/src/lib/controller/store.ts

### Additional context
Add any other context or screenshots about the technical debt here.

**Comment by samayer12** [comment]
Test coverage of `store.ts` is pretty low, I'll want to shore that up before I can confidently refactor. Here's a snippet from `npm run test:unit`:

```
File                  | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
  store.ts            |   16.21 |    12.82 |   17.39 |   16.55 | 19-300
```

**Comment by samayer12** [comment]
After working on this for a bit, it seems like natural spots to refactor are:
* Code Coverage in `store.ts`
* Shared-ish caching logic for two different caches handled by the store
* Consolidating redaction logic to the logger, which is used by the store

**Comment by samayer12** [comment]
#1259 addresses this issue. In general, we introduced the concept of a `storeCache` for cache operations.

Two outstanding items for future work:
* Ensure meaningful test coverage of `store.ts`, which only exposes a constructor
* Extract migration logic from `store.ts` to `storeCache.ts`
